### PR TITLE
Do not swizzle with swizzle

### LINKED ISSUE #1: Error Bad Access with Toast-PhoneGap-Plugin
If using the plugin https://github.com/EddyVerbruggen/Toast-PhoneGap-Plugin
void swizzled_pluginInitialize(id self, SEL _cmd)
{...}
throws an error EXC_BAD_ACCESS(code=2, address...)

### PR DESCRIPTION
**Pull request by zfoltin**
Hopefully fixes #1 and #3

### CODE REVIEW

**Comment by mindhells** [comment]
This is working fine for me, I had a problem when using iBeacons plugin, same as #1.
Thanks

**Comment by helgetan** [comment]
seems to solve the problem

**Comment by mschez** [comment]
This pull request seems to solve the problem. Please merge because this plugin is a dependency of `cordova-plugin-local-notifications` :) and I can't change dependency in `cordova-plugin-local-notifications` without forking it

**Comment by RangerRick** [comment]
I saw this error with the datepicker plugin (which depends on/installs app-event), and can confirm that this PR fixes it for me as well.

**Comment by craigmj** [comment]
Another vote to merge this as soon as possible- I also have encountered the error with local notifications.

**Comment by duepiudue** [comment]
yes for me it work!!

**Comment by coderriot** [comment]
Nice! Seems work! ;)

**Comment by DURK** [comment]
Works for me too :)

**Comment by kozmanbalint** [comment]
Works for me as well (local-notifications-plugin). :-)
Thanks!

**Comment by helgetan** [comment]
@katzer could you merge the pr ?

**Comment by claudiobadii** [comment]
Also works for me... ;-)

**Comment by pmramos** [comment]
+1 --> Please merge =)

**Comment by lbickston** [comment]
+1

**Comment by liranhershko** [comment]
Worked for me too.

**Comment by brunomrpx** [comment]
Works for me :+1:

**Comment by katzer** [comment]
:+1:

**Comment by edismooth** [comment]
+1 Great, it works! I hope you will merge it :)

**Comment by jayasharma** [comment]
Worked for me too :)

**Pull request merged**
